name: recipies_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/env/
    - assets/lotties/

  fonts:
    - family: Nunito-Sans
      fonts:
        - asset: assets/fonts/Nunito-Sans.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf
